# Generated by Django 4.1.4 on 2023-01-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_birthday_cakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alfajores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.BooleanField()),
            ],
        ),
    ]
