# Generated by Django 4.1.4 on 2023-01-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alfajores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday_cakes',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='frozen_cakes',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
