# Generated by Django 4.1.4 on 2023-01-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_alter_birthday_cakes_stock_alter_frozen_cakes_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alfajores',
            options={'verbose_name': 'Alfajor', 'verbose_name_plural': 'Alfajores'},
        ),
        migrations.AlterModelOptions(
            name='birthday_cakes',
            options={'verbose_name': 'Birthday Cake', 'verbose_name_plural': 'Birthday Cakes'},
        ),
        migrations.AlterModelOptions(
            name='frozen_cakes',
            options={'verbose_name': 'Frozen Cake', 'verbose_name_plural': 'Frozen Cakes'},
        ),
    ]
