# Generated by Django 4.1.4 on 2023-02-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_alter_alfajores_options_alter_birthday_cakes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfajores',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='birthday_cakes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='frozen_cakes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
